(function(){if(typeof parjser==="undefined")parjser={};parjser._EOF={type:"_EOF"};parjser._DEBUGGER={type:"_DEBUGGER"};if(!parjser.grammars)parjser.grammars={}})();
(function(){parjser.Exception=function(a,c){this.type=a;c&&this.initFromTokenizer(c);return this};parjser.Exception.prototype={initFromTokenizer:function(a){this.offset=a.offset;this.text=a.originalText;this.initLineAndColumnInfo()},initLineAndColumnInfo:function(){var a=this.offset,c=this.text.substr(0,a),b=c.replace(/\n/g,"");this.line=1+c.length-b.length;b=c.lastIndexOf("\n");this.column=a-b;this.lastLine=c.substr(b,this.column)},toString:function(){return this.type+" at line "+this.line+", column "+
this.column+": "+this.lastLine}};parjser.SyntaxErrorException=function(a,c,b){this.initFromTokenizer(a);this.lastToken=c;this.lastSymbol=b};parjser.SyntaxErrorException.prototype=new parjser.Exception("SyntaxErrorException");parjser.SyntaxErrorException.prototype.toString=function(){return parjser.Exception.prototype.toString.call(this)+"\nwhile parsing "+this.lastSymbol}})();
(function(){parjser.RegexTokenizer=function(a){this.init(a);return this};parjser.RegexTokenizer.prototype={init:function(a){this.tokens=a.tokens?a.tokens:{};this.tokenNames=[null];this.groups=[null];this.ignoreCase=a.ignoreCase===true?true:false;this.ignoredTokens=a.ignoreTokens?a.ignoreTokens:{};this.offset=this.text=null;this.makeRegex(false)},makeRegex:function(a){var c,b=this.tokens,f="",d,e=0,g=this.tokenNames,l=this.groups;for(c in b){if(f!=="")f+="|";d=b[c].toString();f+="("+d.substr(1,d.length-
2)+")";if(a)RegExp("^"+f,(this.ignoreCase?"i":"")+"g");else{g.push(c);d=d.replace(/\\\\/g,"");d=d.replace(/\\\(/g,"");d=d.replace(/\(\?[!:=]/g,"");e++;l.push(e);e+=d.length-d.replace(/\(/g,"").length}}if(!a)try{this.regex=RegExp(f,(this.ignoreCase?"i":"")+"g")}catch(n){this.makeRegex(true)}},isIgnoredToken:function(a){return a.type in this.ignoredTokens},setText:function(a){this.text=this.originalText=a;this.offset=0},next:function(){var a=this.text,c=this.offset,b,f,d,e,g;if(c>=a.length)return parjser._EOF;
if((a=this.regex.exec(a))===null)this.throwNoMatchException();else a.index!==this.offset&&this.throwNoMatchException();b=a[0];f=b.length;g=this.groups;this.offset+=f;e=1;for(d=a.length;e<d;e++)if(a[g[e]])return{text:b,len:f,off:c,type:this.tokenNames[e]};this.throwNoMatchException()},nextToken:function(){for(var a;this.isIgnoredToken(a=this.next()););return a},throwNoMatchException:function(){throw new parjser.Exception("NoMatchFound",this);}}})();
(function(){parjser.SimpleTopDownParser=function(a){this.init(a);this.prune=a.prune;return this};parjser.SimpleTopDownParser.prototype={init:function(a){this.tokens=a.tokens?a.tokens:{};this.tokenizer=a.tokenizer?a.tokenizer:new parjser.RegexTokenizer(a);this.rules=a.rules?a.rules:{};this.startSymbol=a.startSymbol;this.tokenBufferPointer=this.tokenBuffer=null},isToken:function(a){return a in this.tokens},getRule:function(a){var c=this.rules[a];if(!c)throw'No rule found for symbol "'+a+'"';return c},
initTokenBuffer:function(){this.tokenBuffer=[];this.tokenBufferPointer=-1},nextToken:function(){var a;a=++this.tokenBufferPointer;var c=this.tokenBuffer;if(a<c.length)a=c[a];else{a=this.tokenizer.nextToken();c.push(a)}return a},parseRule:function(a,c,b,f){var d,e,g={offset:this.tokenizer.offset,tokenBufferPointer:this.tokenBufferPointer};if(a instanceof Array)e=a.length===0?this.parseEmpty():a[0]==="|"?this.parseChoice(a,g):this.parseSequence(a,g);else if(typeof a==="string")e=a.length===0?this.parseEmpty():
this.parseSymbol(a,g);else if(a===null)e=this.parseEmpty();else if(a===parjser._EOF)if(this.nextToken()===parjser._EOF)d=e=true;else e=false;else if(a===parjser._DEBUGGER){e=true;debugger}else{debugger;throw"Invalid rule: "+JSON.stringify(a);}if(e){g.type=a;g.rulePartIndex=b;g.recurrenceIndex=f;if(c&&d!==true){if(!c.children)c.children=[];g.parentNode=c;c.children.push(g)}}else this.tokenBufferPointer=g.tokenBufferPointer;return e},parseToken:function(a,c){var b=this.nextToken(),f;if(b.type===a){f=
true;c.token=b}else f=false;return f},parseEmpty:function(){return true},parseSequence:function(a,c){var b=a.length,f,d,e,g,l,n;for(f=0;f<b;f++){d=a[f];if(f+1<b){g=a[f+1];switch(g){case "?":l=0;n=1;break;case "*":l=0;n=Number.POSITIVE_INFINITY;break;case "+":l=1;n=Number.POSITIVE_INFINITY;break;default:if((e=/\{(\d+)(,(\d+))?\}/.exec(g))&&e[0]===g){l=e[1]?parseInt(e[1],10):1;n=e[3]?parseInt(e[3],10):1}else{g=null;n=l=1}}}else{g=null;n=l=1}for(e=0;e<l;e++)if(!this.parseRule(d,c,f,e))return false;for(;e<
n;e++)if(!this.parseRule(d,c,f,e))break;g!==null&&f++}return true},parseChoice:function(a,c){var b,f=a.length,d;for(b=1;b<f;b++){d=a[b];if(this.parseRule(d,c,b))return true}return false},parseSymbol:function(a,c){var b;if(this.isToken(a))b=this.parseToken(a,c);else{if(this.tokenBufferPointer===this.tokenBuffer.length-1)this.lastSymbol=a;b=this.getRule(a);b=this.parseRule(b,c)}return b},parse:function(a,c){if(!c)if(this.startSymbol)c=this.startSymbol;else throw"No symbol specified or implied";var b=
[c,parjser._EOF];this.tokenizer.setText(a);this.initTokenBuffer();this.tree={};this.lastSymbol=null;this.parseRule(b,this.tree)||this.throwSyntaxErrorException();return this.tree.children[0].children[0]},throwSyntaxErrorException:function(){var a=this.tokenBuffer,c=a.length;throw new parjser.SyntaxErrorException(this.tokenizer,c?a[c-1]:null,this.lastSymbol?this.lastSymbol:this.currentSymbol);}}})();
(function(){parjser.GrammarCompiler=function(){};parjser.GrammarCompiler.compile=function(a){var c,b,f,d,e=a.rules?a.rules:{},g={},l={tokens:null,tokenizer:null,rules:null,prune:a.prune?true:false};b=(a.parserClass?a.parserClass:parjser.TopDownParser).prototype;var n=b.parseEmpty,u=b.parseChoice,v=b.parseSequence,w=b.parseToken,z=function(i,h){var j,k,o,p,q,t,s,m;h||(h={first:{}});h.originalRule=i;if(i instanceof Array){j=i.length;if(j===0)h.func=n;else{o=[];h.ruleParts=o;if(i[0]==="|"){q=u;k=1}else{q=
v;k=0}h.func=q}for(t=0;k<j;k++){p=i[k];if(typeof p==="undefined")throw"Undefined rulepart at index "+k+" in rule "+JSON.stringify(i);m=p=z(p);k=k;var B=i.length,y=void 0,x=void 0;y=k+1;if(y<B){x=i[y];if(typeof x==="string"){k=y;switch(x){case "?":m.minOccurs=0;m.maxOccurs=1;break;case "+":m.minOccurs=1;m.maxOccurs=Number.POSITIVE_INFINITY;break;case "*":m.minOccurs=0;m.maxOccurs=Number.POSITIVE_INFINITY;break;default:if((match=/^\{(\d+)(,(\d+))?\}$/.exec(x))&&match[0]===x){m.minCardinality=match[1]?
parseInt(match[1],10):1;m.maxCardinality=match[3]?parseInt(match[3],10):1}else k--}}}if(typeof m.minOccurs==="undefined")m.minOccurs=1;if(typeof m.maxOccurs==="undefined")m.maxOccurs=1;k=k;m=p.first;if(q===u||q===v&&t===0)for(s in m){h.first[s]||(h.first[s]={});h.first[s][o.length]=true}t+=p.minOccurs;h.ruleParts.push(p)}if(t===0)h.minOccurs=0}else if(typeof i==="string")if(d[i]){h.token=i;h.func=w;m={};m[i]={"0":true};h.first=m}else if(e[i]){j=g[i];if(!j){j={symbol:i,minOccurs:1,maxOccurs:1,first:{}};
j.first[i]={"0":true};g[i]=j;z(e[i],j)}for(s in j)h[s]=j[s]}else throw i+" is neither a token nor a symbol.";else if(i===null)h.func=n;return h},A=function(i){var h,j,k,o;i.fixed=true;h=i.first;for(j in h){indexes=h[j];if(!(indexes instanceof Array)){o=[];for(k in indexes)o.push(parseInt(k,10));h[j]=o.sort()}}if(i=i.ruleParts){h=i.length;for(j=0;j<h;j++){k=i[j];k.fixed||A(k)}}};if(a.tokens)d=a.tokens;else{d={};r={};for(c in e){b=e[c];if(b instanceof RegExp)d[c]=b;else r[c]=b}e=r}l.tokens=d;c=a.tokenizer?
a.tokenizer:new parjser.RegexTokenizer({tokens:d,ignoreCase:a.ignoreCase,ignoreTokens:a.ignoreTokens});l.tokenizer=c;if(a.startSymbol)f=a.startSymbol;else for(f in e)break;if(!e[f])throw"No rule found for symbol "+f;l.startSymbol=f;z(f);(function(){var i,h,j,k,o,p,q,t,s;for(i in g){h=g[i];k={};h=h.first;for(j in h)if(o=g[j])k[j]=o;for(j in k){s=h[j];delete h[j];if(j!==i){o=k[j];o=o.first;for(p in o)if(!g[p]){q=h[p];if(!q){q={};h[p]=q}for(t in s)q[t]=true}}}}})();(function(){var i,h;for(i in g){h=
g[i];A(h)}})();l.rules=g;l.compiled=true;return l}})();
(function(){parjser.TopDownParser=function(a){this.grammar=a.compiled?a:parjser.GrammarCompiler.compile(a);this.tokenizer=this.grammar.tokenizer;this.prune=this.grammar.prune;return this};parjser.TopDownParser.prototype={initTokenBuffer:function(){this.tokenBuffer=[];this.tokenBufferPointer=-1},nextToken:function(){var a;a=++this.tokenBufferPointer;var c=this.tokenBuffer;if(a<c.length)a=c[a];else{a=this.tokenizer.nextToken();c.push(a)}return a},parseRule:function(a,c){for(var b,f=this.prune,d,e=0,
g=a.func,l=a.maxOccurs;e<l;e++){d=this.tokenBufferPointer;b={children:[]};if(g.call(this,a,b)){b.offset=this.tokenizer.offset;b.tokenBufferPointer=d;b.type=a;b.parentNode=c;if(f){d=b.children.length;if(d===1)b=b.children[0]}c.children.push(b)}else{this.tokenBufferPointer=d;b.children=null;b.parentNode=null;b.type=null;break}}return e>=a.minOccurs},parseEmpty:function(){return true},parseToken:function(a,c){var b=this.nextToken();if(b.type===a.token){c.token=b;return true}else return false},parseEOF:function(){return this.nextToken()===
parjser._EOF},parseChoice:function(a,c){for(var b=0,f=a.ruleParts,d=f.length;b<d;b++)if(this.parseRule(f[b],c))return true;return false},parseSequence:function(a,c){for(var b=0,f=a.ruleParts,d=f.length;b<d;b++)if(!this.parseRule(f[b],c))return false;return true},initParse:function(a,c){if(!c)if(!(c=this.grammar.startSymbol))throw"No symbol specified or implied";var b=this.grammar.rules[c];b={func:parjser.TopDownParser.prototype.parseSequence,ruleParts:[b,parjser._EOF],minOccurs:1,maxOccurs:1};this.tokenizer.setText(a);
this.initTokenBuffer();this.tree={children:[]};return b},parse:function(a,c){this.parseRule(this.initParse(a,c),this.tree)||this.throwSyntaxErrorException();return this.tree.children[0].children[0]},throwSyntaxErrorException:function(){var a=this.tokenBuffer,c=a.length;throw new parjser.SyntaxErrorException(this.tokenizer,c?a[c-1]:null,this.lastSymbol?this.lastSymbol:this.currentSymbol);}};parjser._EOF.func=parjser.TopDownParser.prototype.parseEOF;parjser._EOF.minOccurs=1;parjser._EOF.maxOccurs=1})();
(function(){parjser._EOF.first={};parjser._EOF.first[parjser._EOF.type]=[0];var a=parjser.TopDownParser,c=a.prototype;parjser.TopDownParserWithLookahead=function(b){b.parserClass=parjser.TopDownParserWithLookahead;a.call(this,b)};parjser.TopDownParserWithLookahead.prototype={initTokenBuffer:c.initTokenBuffer,nextToken:c.nextToken,throwSyntaxErrorException:c.throwSyntaxErrorException,parse:c.parse,parseEOF:c.parseEOF,parseEmpty:c.parseEmpty,nextToken:c.nextToken,parseToken:function(b,f){var d=this.lookaheadToken;
if(d.type===b.token){f.token=d;this.lookaheadToken=this.nextToken();return true}else return false},initParse:function(b,f){var d=c.initParse.call(this,b,f);d.func=this.parseSequence;d.first={};var e;for(e in d.ruleParts[0].first)d.first[e]=[0];this.lookaheadToken=this.nextToken();return d},parseRule:function(b,f){var d,e=b.first[this.lookaheadToken.type],g,l,n=0,u,v,w;if(e){l=this.prune;u=b.func;for(v=b.maxOccurs;n<v;n++){w=this.tokenBufferPointer;d=this.lookaheadToken;g={children:[]};if(u.call(this,
b,g,e)){g.offset=this.tokenizer.offset;g.tokenBufferPointer=w;g.type=b;g.parentNode=f;if(l){d=g.children;if(d.length===1)g=d[0]}f.children.push(g)}else{this.tokenBufferPointer=w;this.lookaheadToken=d;g.children=null;g.parentNode=null;g.type=null;break}}}return n>=b.minOccurs},parseChoice:function(b,f,d){b=b.ruleParts;var e,g=d.length;for(e=0;e<g;e++)if(this.parseRule(b[d[e]],f))return true;return false},parseSequence:function(b,f,d){b=b.ruleParts;for(var e=b.length,g=d.length;0<g;){for(d=d[0];d<e;d++)if(!this.parseRule(b[d],
f))return false;return true}}}})();
